# Rime default settings
# encoding: utf-8

config_version: "0.35"

schema_list:
  - schema: luna_pinyin
  - schema: cangjie5
  - schema: luna_pinyin_fluency
  - schema: luna_pinyin_simp
  - schema: luna_pinyin_tw

switcher:
  caption: 〔方案選單〕
  hotkeys:
    - Control+grave
    - Control+Shift+grave
    - F4
  save_options:
    - full_shape
    - ascii_punct
    - simplification
    - extended_charset
  fold_options: true
  abbreviate_options: true
  option_list_separator: '／'

menu:
  page_size: 9

punctuator:
  full_shape:
    ' ' : { commit: '　' }
    ',' : { commit: ， }
    '.' : { commit: 。 }
    '<' : [ 《, 〈, «, ‹ ]
    '>' : [ 》, 〉, », › ]
    '/' : [ ／, ÷ ]
    '?' : { commit: ？ }
    ';' : { commit: ； }
    ':' : { commit: ： }
    '''' : { pair: [ '‘', '’' ] }
    '"' : { pair: [ '“', '”' ] }
    '\' : [ 、, ＼ ]
    '|' : [ ·, ｜, '§', '¦' ]
    '`' : ｀
    '~' : ～
    '!' : { commit: ！ }
    '@' : [ ＠, ☯ ]
    '#' : [ ＃, ⌘ ]
    '%' : [ ％, '°', '℃' ]
    '$' : [ ￥, '$', '€', '£', '¥', '¢', '¤' ]
    '^' : { commit: …… }
    '&' : ＆
    '*' : [ ＊, ·, ・, ×, ※, ❂ ]
    '(' : （
    ')' : ）
    '-' : －
    '_' : ——
    '+' : ＋
    '=' : ＝
    '[' : [ 「, 【, 〔, ［ ]
    ']' : [ 」, 】, 〕, ］ ]
    '{' : [ 『, 〖, ｛ ]
    '}' : [ 』, 〗, ｝ ]
  half_shape:
    ',' : { commit: ， }
    '.' : { commit: 。 }
    '<' : [ 《, 〈, «, ‹ ]
    '>' : [ 》, 〉, », › ]
    '/' : [ 、, '/', ／, ÷ ]
    '?' : { commit: ？ }
    ';' : { commit: ； }
    ':' : { commit: ： }
    '''' : { pair: [ '‘', '’' ] }
    '"' : { pair: [ '“', '”' ] }
    '\' : [ 、, '\', ＼ ]
    '|' : [ ·, '|', ｜, '§', '¦' ]
    '`' : '`'
    '~' : [ '~', ～ ]
    '!' : { commit: ！ }
    '@' : '@'
    '#' : '#'
    '%' : [ '%', ％, '°', '℃' ]
    '$' : [ ￥, '$', '€', '£', '¥', '¢', '¤' ]
    '^' : { commit: …… }
    '&' : '&'
    '*' : [ '*', ＊, ·, ・, ×, ※, ❂ ]
    '(' : （
    ')' : ）
    '-' : '-'
    '_' : ——
    '+' : '+'
    '=' : '='
    '[' : [ 「, 【, 〔, ［ ]
    ']' : [ 」, 】, 〕,  ］ ]
    '{' : [ 『, 〖, ｛ ]
    '}' : [ 』, 〗, ｝ ]

key_binder:
  bindings:
    # Emacs style
    - { when: composing, accept: Control+p, send: Up }
    - { when: composing, accept: Control+n, send: Down }
    - { when: composing, accept: Control+b, send: Left }
    - { when: composing, accept: Control+f, send: Right }
    - { when: composing, accept: Control+a, send: Home }
    - { when: composing, accept: Control+e, send: End }
    - { when: composing, accept: Control+d, send: Delete }
    - { when: composing, accept: Control+k, send: Shift+Delete }
    - { when: composing, accept: Control+h, send: BackSpace }
    - { when: composing, accept: Control+g, send: Escape }
    - { when: composing, accept: Control+bracketleft, send: Escape }
    - { when: composing, accept: Alt+v, send: Page_Up }
    - { when: composing, accept: Control+v, send: Page_Down }
    # paging keys
    - { when: composing, accept: ISO_Left_Tab, send: Page_Up }
    - { when: composing, accept: Shift+Tab, send: Page_Up }
    - { when: composing, accept: Tab, send: Page_Down }
    - { when: has_menu, accept: minus, send: Page_Up }
    - { when: has_menu, accept: equal, send: Page_Down }
    - { when: paging, accept: comma, send: Page_Up }
    - { when: has_menu, accept: period, send: Page_Down }
    # hotkey switch
    - { when: always, accept: Control+Shift+1, select: .next }
    - { when: always, accept: Control+Shift+2, toggle: ascii_mode }
    - { when: always, accept: Control+Shift+3, toggle: full_shape }
    - { when: always, accept: Control+Shift+4, toggle: simplification }
    - { when: always, accept: Control+Shift+5, toggle: extended_charset }
    - { when: always, accept: Control+Shift+exclam, select: .next }
    - { when: always, accept: Control+Shift+at, toggle: ascii_mode }
    - { when: always, accept: Control+Shift+numbersign, toggle: full_shape }
    - { when: always, accept: Control+Shift+dollar, toggle: simplification }
    - { when: always, accept: Control+Shift+percent, toggle: extended_charset }
    - { when: always, accept: Shift+space, toggle: full_shape }
    - { when: always, accept: Control+period, toggle: ascii_punct }

recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: inline_ascii
    Shift_R: commit_text
    Control_L: noop
    Control_R: noop
    Caps_Lock: clear
    Eisu_toggle: clear

speller:
  alphabet: zyxwvutsrqponmlkjihgfedcba

trime:
  keyboard:
  - mode: 0
    keys:
    - {symbol: '“', text: '1'}
    - {symbol: 'abc', text: '2'}
    - {symbol: 'def', text: '3'}
    - {symbol: 'ghi', text: '4'}
    - {symbol: 'jkl', text: '5'}
    - {symbol: 'mno', text: '6'}
    - {symbol: 'pqrs', text: '7'}
    - {symbol: 'tuv', text: '8'}
    - {symbol: 'wxyz', text: '9'}
    - {symbol: ' ”', text: '0'}
    - {symbol: '央王', text: q}
    - {symbol: 'ia.ua', text: w}
    - {symbol: '！', text: e}
    - {symbol: 'uan', text: r}
    - {symbol: 'ie', text: t}
    - {symbol: '英外', text: y}
    - {symbol: 'Zh', text: u}
    - {symbol: 'Sh', text: i}
    - {symbol: 'uo', text: o}
    - {symbol: 'ei', text: p}
    - {width: 5}
    - {symbol: '：', text: a}
    - {symbol: '.ong', text: s}
    - {symbol: 'ai', text: d}
    - {symbol: 'ou', text: f}
    - {symbol: 'en月', text: g}
    - {symbol: 'ang', text: h}
    - {symbol: 'ian', text: j}
    - {symbol: 'un', text: k}
    - {symbol: 'an', text: l}
    - {text: <shift>, width: 12}
    - {symbol: 'eng', text: z}
    - {symbol: 'in', text: x}
    - {symbol: 'ao', text: c}
    - {symbol: 'Chui',text: v}
    - {symbol: '；',text: b}
    - {symbol: 'iu', text: n}
    - {symbol: 'iao', text: m}
    - {text: <delete>, width: 18}
    - {label: "中", switch: 1, text: <switch>, width: 12}
    - {label: '九键', switch: 2, text: <switch>, symbol: '...', symbolCode: -11, width: 12}
    - {symbol: '、', text: '，', width: 15}
    - {text: <space>, width: 22}
    - {symbol: '？', text: '。', width: 15}
    - {text: <enter>, width: 24}
  - mode: 1
    keys:
    - {symbol: '!', text: '1'}
    - {symbol: '@', text: '2'}
    - {symbol: '#', text: '3'}
    - {symbol: '$', text: '4'}
    - {symbol: '%', text: '5'}
    - {symbol: '^', text: '6'}
    - {symbol: '&', text: '7'}
    - {symbol: '*', text: '8'}
    - {symbol: '(', text: '9'}
    - {symbol: ')', text: '0'}
    - {symbol: '~', text: q}
    - {symbol: '`', text: w}
    - {symbol: '+', text: e}
    - {symbol: '=', text: r}
    - {symbol: '<', text: t}
    - {symbol: '>', text: y}
    - {symbol: '{', text: u}
    - {symbol: '}', text: i}
    - {symbol: '[', text: o}
    - {symbol: ']', text: p}
    - {width: 5}
    - {symbol: '_', text: a}
    - {symbol: '-', text: s}
    - {symbol: '/', text: d}
    - {symbol: '|', text: f}
    - {symbol: '\', text: g}
    - {symbol: "'", text: h}
    - {symbol: '"', text: j}
    - {symbol: ':', text: k}
    - {symbol: ';', text: l}
    - {text: <shift>, width: 12}
    - {symbol: '^_^',text: z}
    - {symbol: '⊙o⊙',text: x}
    - {symbol: '‧_‧?',text: c}
    - {symbol: '囧',text: v}
    - {symbol: '>_<',text: b}
    - {symbol: 'T_T',text: n}
    - {symbol: '¬_¬',text: m}
    - {text: <delete>, width: 18}
    - {label: "英", switch: 0, text: <switch>, width: 12}
    - {label: '九键', switch: 2, text: <switch>, width: 12}
    - {text: ',', width: 15}
    - {text: <space>, width: 22}
    - {symbol: '?', text: '.', width: 15}
    - {text: <enter>, width: 24}
  - mode: 0
    width: 22
    keys:
    - {symbol: '“',text: '（', width: 17}
    - {text: '1'}
    - {symbol: 'abc', text: '2'}
    - {symbol: 'def', text: '3'}
    - {text: <delete>, width: 17}
    
    - {symbol: '：',text: '、', width: 17}
    - {symbol: 'ghi', text: '4'}
    - {symbol: 'jkl', text: '5'}
    - {symbol: 'mno', text: '6'}
    - {symbol: '”', text: '）', width: 17}

    - {symbol: '；',text: '，', width: 17}  
    - {symbol: 'pqrs', text: '7'}
    - {symbol: 'tuv', text: '8'}
    - {symbol: 'wxyz', text: '9'}
    - {symbol: '！',text: '。', width: 17}


    - {text: <switch>, switch: 0, width: 13}
    - {symbol: '/', text: '.', width: 12}
    - {symbol: '\', text: '？', width: 14}
    - {text: <space>,width: 22}
    - {text: '0', width: 22}
    - {text: <enter>, width: 17}
    
    
